# Generated by Django 4.1.5 on 2023-02-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0006_profile_email_profile_name_profile_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
