# Generated by Django 4.1.5 on 2023-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0007_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo_list",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="todo_list",
            name="text",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
