# Generated by Django 4.1.5 on 2023-03-02 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0011_rename_to_do_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("Name", models.TextField(blank=True, null=True)),
                ("dificulty", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=20)),
                ("number", models.IntegerField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("owner", models.ManyToManyField(blank=True, to="users_app.profile")),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="exercises",
            field=models.ManyToManyField(blank=True, to="users_app.exercise"),
        ),
    ]
