# Generated by Django 4.1.5 on 2023-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0013_exercise_exemple1_exercise_exemple2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="tag_name",
            field=models.CharField(default="None", max_length=10),
        ),
    ]
