# Generated by Django 4.1.5 on 2023-03-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0014_exercise_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="Exemple3",
        ),
        migrations.AddField(
            model_name="exercise",
            name="Answer1default",
            field=models.CharField(default="NONE", max_length=200),
        ),
        migrations.AddField(
            model_name="exercise",
            name="Answer1user",
            field=models.CharField(default="NONE", max_length=200),
        ),
        migrations.AddField(
            model_name="exercise",
            name="Answer2default",
            field=models.CharField(default="NONE", max_length=200),
        ),
        migrations.AddField(
            model_name="exercise",
            name="Answer2user",
            field=models.CharField(default="NONE", max_length=200),
        ),
        migrations.AddField(
            model_name="exercise",
            name="Default",
            field=models.TextField(default="None", max_length=500),
        ),
    ]
