# Generated by Django 4.1.5 on 2023-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0015_remove_exercise_exemple3_exercise_answer1default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="description",
            field=models.TextField(default="NONE", max_length=1000),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="Name",
            field=models.CharField(default="NONE", max_length=50),
        ),
    ]
