# Generated by Django 4.1.5 on 2023-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0016_exercise_description_alter_exercise_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="Answer1default",
            field=models.TextField(default="NONE", max_length=200),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="Answer1user",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="Answer2default",
            field=models.TextField(default="NONE", max_length=200),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="Answer2user",
            field=models.TextField(max_length=200),
        ),
    ]
