# Generated by Django 4.1.5 on 2023-03-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0017_alter_exercise_answer1default_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="exercises",
        ),
    ]
