# Generated by Django 4.1.5 on 2023-03-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0018_remove_profile_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exercises",
            field=models.ManyToManyField(blank=True, to="users_app.exercise"),
        ),
    ]
