# Generated by Django 4.1.5 on 2023-03-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0019_profile_exercises"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="Answer1user",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="Answer2user",
        ),
    ]
