# Generated by Django 4.1.5 on 2023-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0020_remove_exercise_answer1user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="Help",
            field=models.TextField(default="NONE", max_length=500),
        ),
    ]
