# Generated by Django 4.1.5 on 2023-03-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0021_exercise_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="Code",
            field=models.TextField(default="NONE", max_length=5000),
        ),
    ]
