# Generated by Django 4.1.5 on 2023-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0023_exercise_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="Image",
            field=models.ImageField(
                blank=True,
                default="profiles/default_profile.png",
                null=True,
                upload_to="ex_easy/",
            ),
        ),
    ]
