# Generated by Django 4.1.5 on 2023-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0024_alter_exercise_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="level",
            field=models.CharField(blank=True, default="Beginners", max_length=10),
        ),
    ]
